use_frameworks!

target 'PinpointKitExample' do
	pod 'PinpointKit', :path => '../'
end


# The following is a workaround for a Mach-O header that occurs when building `PinpointKitExample` since Xcode 8 Beta 2.
# The issue, along with the proposal of this workaround, are discussed at https://github.com/CocoaPods/CocoaPods/issues/5598
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
